name: formbuilder_v2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  responsive_builder: ^0.7.0

# from 1gov
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1
  icons_launcher: ^2.1.3
  flutter_animate: ^4.1.1+1
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  dio: ^5.3.0
  dio_smart_retry: ^5.0.0
  enum_to_string: ^2.0.1
  font_awesome_flutter: ^10.5.0
  universal_html: ^2.2.3
  path_provider: ^2.0.15
  package_rename: ^1.3.3
  flutter_local_notifications: ^15.1.0+1
  fluttertoast: ^8.2.2
  typicons_flutter: ^0.5.0
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.12
  rive: ^0.7.16
  eva_icons_flutter: ^3.1.0
  package_info_plus: ^4.0.2
  cached_network_image: ^3.2.3
  random_string: ^2.3.1
  sn_progress_dialog: ^1.1.3
  flutter_markdown: ^0.6.17
  pinput: ^2.2.31
  otp_timer_button: ^1.1.0
  password_strength_checker: ^1.2.2
  style_cron_job: ^1.0.4+2
  dart_jsonwebtoken: ^2.8.2
  searchable_listview: ^2.8.0
  slugid: ^1.1.2
  flutter_typeahead: ^4.6.2
  flutter_keyboard_visibility: ^5.4.1
  expandable_richtext: ^1.0.3
  badges: ^3.1.1
  js: ^0.6.7
  url_strategy: ^0.2.0




# form builder
  flutter_form_builder: ^9.1.1
  form_builder_extra_fields: ^10.1.0
  form_builder_cupertino_fields: ^0.2.1
  
# form packages
  reactive_forms: ^16.0.2
  reactive_file_picker: ^2.0.0
  group_button: ^5.3.2
  reactive_phone_form_field: ^2.0.0
  currency_picker: ^2.0.16
  extended_masked_text: ^2.3.1
  reactive_date_time_picker: ^3.0.0
  reactive_date_range_picker: ^2.0.0
  reactive_dropdown_search: ^3.0.0
  reactive_advanced_switch: ^2.0.0
  reactive_flutter_typeahead: ^2.1.0

# appwrite
  appwrite: ^9.0.1
  dart_appwrite: ^8.0.1


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800

